# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: index_admin.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'index_admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11index_admin.proto\x12\x0fraguao.index.v1\"\x07\n\x05\x45mpty\"4\n\rIngestRequest\x12\x12\n\nfile_match\x18\x01 \x01(\t\x12\x0f\n\x07rebuild\x18\x02 \x01(\x08\"\x9e\x01\n\x0eIngestProgress\x12\x10\n\x08\x64oc_name\x18\x01 \x01(\t\x12\x0e\n\x06\x63hunks\x18\x02 \x01(\x05\x12\x0f\n\x07seconds\x18\x03 \x01(\x02\x12\x11\n\ttoken_p50\x18\x04 \x01(\x05\x12\x11\n\ttoken_p90\x18\x05 \x01(\x05\x12\x11\n\ttoken_max\x18\x06 \x01(\x05\x12\x0c\n\x04\x64one\x18\x07 \x01(\x05\x12\x12\n\ntotal_docs\x18\x08 \x01(\x05\"%\n\x0bPruneResult\x12\x16\n\x0eremoved_chunks\x18\x01 \x01(\x05\"a\n\x13IndexStatusResponse\x12\x0e\n\x06\x63hunks\x18\x01 \x01(\x05\x12\x11\n\tdocuments\x18\x02 \x01(\x05\x12\x17\n\x0f\x65mbedding_model\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t2\xea\x01\n\nIndexAdmin\x12K\n\x06Ingest\x12\x1e.raguao.index.v1.IngestRequest\x1a\x1f.raguao.index.v1.IngestProgress0\x01\x12\x42\n\nPruneIndex\x12\x16.raguao.index.v1.Empty\x1a\x1c.raguao.index.v1.PruneResult\x12K\n\x0bIndexStatus\x12\x16.raguao.index.v1.Empty\x1a$.raguao.index.v1.IndexStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'index_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_INGESTREQUEST']._serialized_start=47
  _globals['_INGESTREQUEST']._serialized_end=99
  _globals['_INGESTPROGRESS']._serialized_start=102
  _globals['_INGESTPROGRESS']._serialized_end=260
  _globals['_PRUNERESULT']._serialized_start=262
  _globals['_PRUNERESULT']._serialized_end=299
  _globals['_INDEXSTATUSRESPONSE']._serialized_start=301
  _globals['_INDEXSTATUSRESPONSE']._serialized_end=398
  _globals['_INDEXADMIN']._serialized_start=401
  _globals['_INDEXADMIN']._serialized_end=635
# @@protoc_insertion_point(module_scope)
