# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from asistente_agentico_uao.grpc_impl.stubs import (index_admin_pb2 as index__admin__pb2)

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in index_admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndexAdminStub:
    """Plano de control de ingesta (Fase 5): administración del índice Chroma.

    Separación de funciones con la API REST (api/main.py, :8000):
    - REST = consulta pública (POST /ask, GET /health, GET /documents):
    solo LEE el índice y llama al LLM; cara al frontend.
    - gRPC = control plane interno: operaciones de ESCRITURA sobre el índice
    (ingesta, prune, estado), máquina-a-máquina, con progreso en streaming.
    Este servicio NO duplica /ask.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_stream(
                '/raguao.index.v1.IndexAdmin/Ingest',
                request_serializer=index__admin__pb2.IngestRequest.SerializeToString,
                response_deserializer=index__admin__pb2.IngestProgress.FromString,
                _registered_method=True)
        self.PruneIndex = channel.unary_unary(
                '/raguao.index.v1.IndexAdmin/PruneIndex',
                request_serializer=index__admin__pb2.Empty.SerializeToString,
                response_deserializer=index__admin__pb2.PruneResult.FromString,
                _registered_method=True)
        self.IndexStatus = channel.unary_unary(
                '/raguao.index.v1.IndexAdmin/IndexStatus',
                request_serializer=index__admin__pb2.Empty.SerializeToString,
                response_deserializer=index__admin__pb2.IndexStatusResponse.FromString,
                _registered_method=True)


class IndexAdminServicer:
    """Plano de control de ingesta (Fase 5): administración del índice Chroma.

    Separación de funciones con la API REST (api/main.py, :8000):
    - REST = consulta pública (POST /ask, GET /health, GET /documents):
    solo LEE el índice y llama al LLM; cara al frontend.
    - gRPC = control plane interno: operaciones de ESCRITURA sobre el índice
    (ingesta, prune, estado), máquina-a-máquina, con progreso en streaming.
    Este servicio NO duplica /ask.

    """

    def Ingest(self, request, context):
        """Ingresa markdowns al índice; emite progreso por documento en vivo.
        Idempotente (IDs sha256(doc_name+chunk_index)); rebuild borra antes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PruneIndex(self, request, context):
        """Borra chunks de documentos ausentes en markdown_dir.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexStatus(self, request, context):
        """Estado del índice: chunks, documentos, modelo de embeddings, device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ingest': grpc.unary_stream_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=index__admin__pb2.IngestRequest.FromString,
                    response_serializer=index__admin__pb2.IngestProgress.SerializeToString,
            ),
            'PruneIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.PruneIndex,
                    request_deserializer=index__admin__pb2.Empty.FromString,
                    response_serializer=index__admin__pb2.PruneResult.SerializeToString,
            ),
            'IndexStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexStatus,
                    request_deserializer=index__admin__pb2.Empty.FromString,
                    response_serializer=index__admin__pb2.IndexStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raguao.index.v1.IndexAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('raguao.index.v1.IndexAdmin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IndexAdmin:
    """Plano de control de ingesta (Fase 5): administración del índice Chroma.

    Separación de funciones con la API REST (api/main.py, :8000):
    - REST = consulta pública (POST /ask, GET /health, GET /documents):
    solo LEE el índice y llama al LLM; cara al frontend.
    - gRPC = control plane interno: operaciones de ESCRITURA sobre el índice
    (ingesta, prune, estado), máquina-a-máquina, con progreso en streaming.
    Este servicio NO duplica /ask.

    """

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/raguao.index.v1.IndexAdmin/Ingest',
            index__admin__pb2.IngestRequest.SerializeToString,
            index__admin__pb2.IngestProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PruneIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raguao.index.v1.IndexAdmin/PruneIndex',
            index__admin__pb2.Empty.SerializeToString,
            index__admin__pb2.PruneResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raguao.index.v1.IndexAdmin/IndexStatus',
            index__admin__pb2.Empty.SerializeToString,
            index__admin__pb2.IndexStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
